### ISSUE TITLE
Wrong value min used (from other type of items) for relisting cards.

### ISSUE THREAD

**Issue by Omicron666** [Nuklon/Steam-Economy-Enhancer#16] opened 2017-04-30 03:17 UTC
Hello,
Nice update for 4.0.0

I loaded http://steamcommunity.com/market/listings/753/516700-You%27ve%20Got%20Heart
It is using min value of other items, it first relisted for 0,05, then tried 0,04 min value for other items, then it got relisted for 0,04...

You will notice it is highlighted in green.
http://i.imgur.com/uAYJtAc.png
http://i.imgur.com/xqd8cHC.png

**Comment by Nuklon** [comment] 2017-04-30 11:05
Well, luckily I've that card too (4 of them in fact), but it's all 5 cents here and it's detected as a trading card.

What is happening is that you have Steam on French. Market listings do not have an identifier for the items to let me know that it's a trading card of another item, which means I have to check for the text ('trading card'), which doesn't exist in french. This same problem exists for other languages of course. 

That said, I noticed there's one extra variable that I can use to check if it's a trading card or not and I've implemented this and pushed a fix out 👍

**Closed** 2017-04-30 11:04 UTC

**Comment by Botan626** [comment] 2017-05-21 15:51
Hi.

SEE puts wrong min price, the settings are: lowest listing and -0.01.

But, it doesn't subtract -0.01 and puts the same lowest selling price on my item.

**Comment by Nuklon** [comment] 2017-05-22 07:24
@Botan626 
It respects the minimum and maximum prices you've set. If you want to change that behavior you have to lower the minimum price per item.

**Comment by Botan626** [comment] 2017-05-22 07:41
The minimum price is set way lower than the minimum selling price on market.

**Comment by Nuklon** [comment] 2017-05-24 17:49
I can't reproduce that, if you have one item that always causes this you can send me a [trade offer](https://steamcommunity.com/tradeoffer/new/?partner=94613954&token=6OR2RY2I) and I'll try to reproduce it with that item.

**Comment by Botan626** [comment] 2017-05-24 17:58
This happens for each my item.

Here's example: the background was listed for 5,69 Rub, after I hit relist overpriced SEE relisted it with the same price as lowest selling one. The settings you can see in the screenshot also.

http://imgur.com/a/aZSvI

**Comment by Botan626** [comment] 2017-05-26 11:58
I keep experiencing such behaviour, with cards at present time.

Am I doing anything wrong?

**Comment by Nuklon** [comment] 2017-05-27 18:32
No, the offset is applied only in inventory. Otherwise it would relist the item cheaper and cheaper again as it would then see your listing as overpriced. I don't know if this behavior can be changed, maybe with the new item information I can check if its our own listing but I don't think so.

**Comment by Botan626** [comment] 2017-05-27 18:38
"Otherwise it would relist the item cheaper and cheaper again as it would then see your listing as overpriced."  ---  If my item is listed with the price 0.01 lower than next selling item, how come it can be considered overpriced?

What is an overpriced item for this script then? And why it will relist overpriced items for the same actual selling price? What's the point in it?

**Comment by Nuklon** [comment] 2017-05-28 08:12
Because there's no information if _your_ item is the only item with the lowest listing price. If you would always apply the offset (a negative one) you would constantly relist it with that offset applied and thus eventually sell it for the minimum price in the options.

That said, I thought about this and it's somewhat possible to still apply the offset. I'll upload a new version in a minute or so.

**Comment by Botan626** [comment] 2017-05-28 10:36
"Because there's no information if your item is the only item with the lowest listing price."  --- there is no way to determine the quantity of items selling at the lowest price?

Anyway, the new version works fine, the items are marked as underpriced now, but it's no big deal.

Thank you.

**Comment by Nuklon** [comment] 2017-05-28 10:38
Well, there sort of is, but that data is not reliable. Otherwise I'd have to load all pages on Steam again and then you'd have a way slower check as it's rather rate limited.

Underpriced items haven't changed, that's still the same.
