### ISSUE TITLE
Infinite "Loading market listings"

### ISSUE THREAD

**Issue by yarushi** [Nuklon/Steam-Economy-Enhancer#8] opened 2017-04-02 18:04 UTC
I would like to refresh my item prices but keep showing this "Loading market listings"

![ac3ead233af04a93b6a67ed645203e22](https://cloud.githubusercontent.com/assets/26856967/24589719/a5d72fc0-17b5-11e7-8032-d37117376cce.png)

**Comment by Nuklon** [comment] 2017-04-03 14:00
Several questions:

- What browser are you using?
- Does it work if you change Steam's language to English?
- Does it work if you do a hard refresh (ctrl+f5)?

**Comment by yarushi** [comment] 2017-04-04 18:49
1) Chrome
2) Not working with English too
3) Not working with hard refresh too

**Comment by Nuklon** [comment] 2017-04-07 17:56
Alright, I can't reproduce it. I've tested it on 3 different machines (Chrome + Firefox) and it's working on all of them. Maybe you can try it on another browser?

**Comment by Sparh4wk** [comment] 2017-04-10 08:04
have exactly the same problem :( infinite loading market listings :(

**Comment by Nuklon** [comment] 2017-04-10 08:21
Does anything related to an error show up in the developer's console (F12)?
I'd like to fix it of course but as I can't reproduce it it's impossible for me.

**Comment by Sparh4wk** [comment] 2017-04-10 08:26
Dunno if its related.. on chrome Ive got this after market refresh.
![i63uh2z](https://cloud.githubusercontent.com/assets/7014826/24852531/2464da22-1dd8-11e7-9d9d-6a98bfb63529.png)

**Comment by Nuklon** [comment] 2017-04-10 12:08
I don't think so, no, I have that as well and it's working fine here.
If you log network connections (Net) in Firefox, does anything show up there?
It should make connections such as:
http://steamcommunity.com/market/mylistings?count=100&start=0
http://steamcommunity.com/market/mylistings?count=100&start=100

If you manually enter that url in the browser, what do you see?

**Comment by Sparh4wk** [comment] 2017-04-10 13:25
yes, if I enter that urls to chrome or firefox, it does print info about my listings.

**Comment by Nuklon** [comment] 2017-04-11 08:51
Alright, so that's at least working then. I pretty much need someone with this issue that has some coding experience and can help me debug this.

**Comment by Omicron666** [comment] 2017-04-18 16:14
Hello, thanks for your great script.
I think also had this problem... I don't know how I fixed it....
Maybe just (dis)enabling the userscript. Or messing with EnhancedSteam.

Also, the page navigation disappear : http://i.imgur.com/i3DO7HX.png

**Comment by Nuklon** [comment] 2017-04-19 08:08
Page navigation is removed as all listings are loaded, it's pointless.

**Comment by Omicron666** [comment] 2017-04-19 19:03
The page only lists 100 items : http://i.imgur.com/onUzqTi.png
While I have 1000+ items for sale.

**Comment by Omicron666** [comment] 2017-04-19 19:19
http://i.imgur.com/hN2CnG6.png :P

**Comment by Omicron666** [comment] 2017-04-19 19:25
Fixing it and making it display 1000+ market items is very heavy at the moment anyway...

**Comment by yarushi** [comment] 2017-04-19 19:41
Not working with firefox too :/

**Comment by Omicron666** [comment] 2017-04-19 20:01
Here a quick-fix to apply : http://i.imgur.com/gO5V1O1.png but be aware page will be slow at beginning if you have lots of items on sale...

**Comment by yarushi** [comment] 2017-04-19 20:14
Thanks, It's working now. But the relist button seems get removed, or is it just here ?

**Comment by Sparh4wk** [comment] 2017-04-20 08:02
so I just found a weird thing... 
if my market list is < 10 items = infinite loading
if my martket list is > 10 items = I can see list without infinite loading

hopefully this will helps you :)

**Comment by Nuklon** [comment] 2017-04-20 18:26
Alright, I don't have 1000+ items so I couldn't test that. I already had a function to replace non numbers so I've changed that.

I have about 800 listings at market place without any performance issues (Firefox). Ideally I'd like to keep the pagination but this is problematic because the content is loaded async (every time to go to another page, even back) it's hard to show progress or any kind of feedback that's useful to the user. I think I can add some 3rd party pagination, I'll check it out later.

Regarding the listings, I'm not sure why that happens with < 10 items. Did you find any reason why?

**Comment by Omicron666** [comment] 2017-04-20 19:21
I haven't looked for < 10 items yet.

I have tested main market page. With 2000+ listed items. (thanks to your script !)
Script's performance is MUCH better on Firefox than Chrome !
And performance tools much better and useful in a first approach... (but afaik, sadly Firefox doesn't offer unminifying on the fly)
Also, I found a typo... not sure how _g_bmarketwindowhidden_ is working, though.
_injectjs_ unknown, because it is supposed to be _injectJs_ http://i.imgur.com/FjgZq1v.png

**Comment by Omicron666** [comment] 2017-04-20 19:23
Oh, and those buttons appears on Firefox... but not in Chrome http://i.imgur.com/3ptBGTP.png

**Comment by Sparh4wk** [comment] 2017-04-20 19:30
nope I didnt find anything, why < 10 items = infinite loading :( 
but I can say for sure, that there is something wrong.. tryed that several times, and always same result

**Comment by Nuklon** [comment] 2017-04-22 11:33
Firefox absolutely has a unminify option (Automatically black box minified sources).
I personally only use Firefox, never been a fan of Chrome.

For some reason the injectJs code was put to lower case, not sure when that happened but it's an easy fix (already did that).

I'll investigate the < 10 items bug too, I'll just have to remove all my 800 listings and try again, it's not that hard. I'm currently adding some pagination and a search for market listings, but I still need to style it.

**Comment by Nuklon** [comment] 2017-04-23 14:49
Please try out 3.5.0 :)

**Comment by Sparh4wk** [comment] 2017-04-23 15:19
niiiiiiice 👍 its working now

**Comment by Nuklon** [comment] 2017-04-24 09:17
Including < 10 items?

**Comment by Sparh4wk** [comment] 2017-04-24 12:09
yes, good job! 👍

**Comment by Omicron666** [comment] 2017-04-25 07:17
It works quite well.
- Actually, there must be a conflict issue with EnhancedSteam that causes performance drop (tested on Chrome).
After disabling EnhancedSteam, market listing on main page is MUCH faster.
- sort by price : ok
- sort by name : seems ok apart for 2 items placed before the others.
- sort by date : random/unconsistant
- search item : nice feature. It doesn't search for ":" though.
- still using max price for items that have no buy offers (or recent transactions ?) o_O
- misplaced search box here : http://steamcommunity.com/market/listings/753/Snowflake%20Skin
I get that : in that kind of item pages : http://i.imgur.com/0jI2idZ.png

**Comment by Nuklon** [comment] 2017-04-25 10:48
I'm not using Enhanced Steam, I already made some changes regarding sorting and ES but I'm not really looking into coding a ton of extra stuff just to get around it. I accept PRs for this if anyone is feeling up to it.

Regarding the sorting: price is easy, as it's just a few numbers. sorting by name too (just using default js sort). Sort by date relies on Date.js, If there's a better library it shouldn't be too hard to use but I've yet to find one (+ localized preferably). It works rather well in English at least.
 
The misplaced search box, there shouldn't be on for those listings, should be fixable.

**Comment by Nuklon** [comment] 2017-04-25 11:00
BTW, the maximum price is used for items that have no sell orders. Buy orders are only used if their price exceeds the calculated price (extremely unlikely) or if their price exceeds your maximum defined price (for example, you have the max set to 25 cents, a buy order wants to give 30 cents -> it will list it for 30 cents). This is the expected behavior and it's what I want, it doesn't make sense from an economic point of view to take your minimum price for example.

**Comment by Omicron666** [comment] 2017-04-25 11:09
I am talking about that kind of cases : http://i.imgur.com/jOSskWG.png
No buying offers => the autosell will use max price. At least, that is what I get like 99% of cases.
Though, it doesn't matter for me anymore. Everything from my inventory went on sale. And I (or anyone) can force very low max price if needed.

About ES :
As ES is quite use, some people might want to be aware of temporary fix when they want to use Steam-Economy-Enhancer.
As ES is injecting scripts a bit everywhere on Steam, it should ES responsibility to offer more options to disable what it does on market page.

**Comment by Nuklon** [comment] 2017-04-25 11:13
Can you also send me one of these cards that's 100% certain causing issues? This should also be fixed then 👍

**Comment by Nuklon** [comment] 2017-04-29 09:14
Fixed the search box, the rest seems to fixed in here.

**Closed by Nuklon** 2017-04-29 09:14 UTC
Labels: bug, help wanted

**Comment by Botan626** [comment] 2017-05-18 15:02
Hello. Just installed this extension, and I'm having this issue.

**Comment by Sparh4wk** [comment] 2017-05-18 15:30
yes, the issue < 10 = infinite loading is back :(

**Comment by Omicron666** [comment] 2017-05-18 15:55
yarushi lately too, but fixed it by resetting his browser.

**Comment by Nuklon** [comment] 2017-05-19 15:06
I'll investigate this again.

**Comment by Nuklon** [comment] 2017-05-19 15:22
I think I found the problem and have fixed it, will upload a new version in a sec.
