### ISSUE TITLE
pause for sale listing confirmations after 250 items

### ISSUE THREAD

**Issue by jbmccune** [Nuklon/Steam-Economy-Enhancer#115] opened 2019-01-25 15:43 UTC
For now, I threw a check in "var sellQueue = async.queue..." to stop after 250 items and just pop up an alert so I can go confirm everything before starting another batch, but it would be nice if that was built-in a little more smoothly.

**Comment by Nuklon** [comment] 2019-01-25 15:49
Yes, that would be useful due to Steam market listings limit (although I don't think there's an API to check how many unconfirmed listings there are at the moment, which would be even better). Feel free to submit a PR for this 👍

**Comment by jbmccune** [comment] 2019-01-25 16:12
I'm not much of a modern dev, more of a tinkerer/hack at this point.  I might attempt to work my way through the code to find a proper/elegant way to implement this, but my initial attempt resulted in throwing my hands in the air and dropping in hackery to achieve the minimum result I wanted in a crappy way. :)

Ideally, the entire queue of items would be built and begin processing, and it would just pause every 250/x items with a message to go confirm the listings - then you click a button and it continues with 251/x.  What I did goes through 250/250, then pops up an alert, then when you acknowledge the alert you have to click Sell All Cards (or whatever) again, at which point it continues with 251/500 being displayed, and so on.  That's not ideal, but I couldn't figure out how to more properly pause and resume the queue after a certain number of items.

**Comment by Nuklon** [comment] 2023-06-30 08:29
Closing as Steam no longer requires confirmation for cheap items.

**Closed by Nuklon** 2023-06-30 08:29 UTC
Labels: enhancement, help wanted
