### ISSUE TITLE
Can't sell Items

### ISSUE THREAD

**Issue by Jack-Spirio** [Nuklon/Steam-Economy-Enhancer#26] opened 2017-06-15 23:01 UTC
Since a few days this always show up when I try to sell items:
These items cannot be added to the market...

**Comment by LegendarySpark** [comment] 2017-06-16 09:23
Same for me. Since 4.9.0 (up to 5.2.0), I haven't been able to use either "sell all cards" or marking a few and selling those, since both actions yield this error message. Only selling one card at a time would work. 

I downgraded to 4.8.5 and that version still works for me.

**Comment by Nuklon** [comment] 2017-06-16 10:42
Which browser are you all using? Including the version number please.

**Comment by Carlmundo** [comment] 2017-06-16 11:32
Same for me on 2 different computers running:
Chrome Version 59.0.3071.104 (Official Build) (64-bit)

**Comment by LegendarySpark** [comment] 2017-06-16 13:30
Chrome 58.0.3029.110 (64-bit) & Firefox 53.0.3 (64-bit).

**Comment by Nuklon** [comment] 2017-06-16 14:29
`g_ActiveInventory.m_rgAssets ` is empty on Chrome, which causes this problem. I'm not sure why that's empty on Chrome but filled all the time in Firefox.

**Comment by Nuklon** [comment] 2017-06-16 17:55
It seems Valve changed something again, I think I've it fixed.

**Comment by Botan626** [comment] 2017-06-16 18:39
Just experienced this issue.

**Comment by MonthOLDpickle** [comment] 2017-06-16 22:59
Having this issue now.

Vivaldi - 	1.9.818.50 

(Happens in FF and chrome for me)

**Comment by Nuklon** [comment] 2017-06-17 08:30
Can any of you check if it's working right now? It works fine on all my browsers here 😄

**Comment by LegendarySpark** [comment] 2017-06-17 09:12
Seems good! I just used 5.3.1 (in Chrome) to sell last night's batch of cards with no issue.

**Comment by Nuklon** [comment] 2017-06-17 09:56
Great to hear. It's very strange that I can't reproduce this issue on any browser, I think some scripts from Steam are different here (CDN perhaps). Would like some more confirmations before I'm closing this.

**Comment by Botan626** [comment] 2017-06-17 11:05
Overpriced item is still yellow.

**Comment by Nuklon** [comment] 2017-06-17 11:33
That's a different issue.

**Comment by drabelincoln** [comment] 2017-06-17 18:06
Its still not working for me..just installed the latest version and I'm still getting the "These items cannot be added to the market..." message.

**Comment by Botan626** [comment] 2017-06-17 23:31
Not working for me neither.

**Comment by MonthOLDpickle** [comment] 2017-06-18 07:54
> Can any of you check if it's working right now? It works fine on all my browsers here 

Still no dice

**Comment by Nuklon** [comment] 2017-06-18 12:19
Can you check if new version works?

**Comment by MonthOLDpickle** [comment] 2017-06-18 12:57
> Can you check if new version works?

Now it says "not added to market."

Did a setting change on my end now? At least something else is happening -.-

**Comment by drabelincoln** [comment] 2017-06-21 01:01
New version is working for me.

**Comment by MonthOLDpickle** [comment] 2017-06-26 09:46
Still can't sell massive amounts (2 or more basically).

Get: 1/2 XXXX not added to market.

**Closed** 2017-08-17 06:45 UTC
Labels: help wanted
